version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5

    working_directory: /go/src/github.com/Adron/twitzin
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Enable GoModules
          command: echo 'export GO111MODULE=on' >> $BASH_ENV

      - run:
          name: Build application
          command: go build