# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Enable GoModules
          command: echo 'export GO111MODULE=on' >> $BASH_ENV

      - run:
          name: Build application
          command: go build